### ISSUE TITLE
crash on 0.10.x

### ISSUE THREAD

**Issue by bvdbos** [johnsmarius/nl.philips.jointspace#6]
Stack trace:

TypeError: Cannot read property 'ipaddress' of undefined
at Object.<anonymous> (/drivers/jointspace/driver.js:72:22)
at emitTwo (events.js:87:13)
at Object.emit (events.js:172:7)
at /homey-app/manager/flow.js:1:417
at /homey-app/helpers/client.js:1:1013
at Array.forEach (native)
at process.<anonymous> (/homey-app/helpers/client.js:1:982)
at emitTwo (events.js:87:13)
at process.emit (events.js:172:7)
at internal/child_process.js:696:12

Exit code: 1

**Comment by bvdbos** [comment]
fixed with 0.5.x... Thanks!
